"""
Integration tests: /fees/*, including the Milestone 8 mandatory Fees
Domain Rules, VR-008, and invoice auto-generation, end-to-end.

Full request -> DB -> response cycle against a disposable test database
(see tests/conftest.py). Requires TEST_DATABASE_URL — skipped otherwise.
"""

from tests.conftest import requires_test_database

pytestmark = requires_test_database


def _login(client, email: str, password: str) -> str:
    response = client.post("/api/v1/auth/login", json={"email": email, "password": password})
    assert response.status_code == 200
    return response.json()["access_token"]


def _headers(token: str) -> dict[str, str]:
    return {"Authorization": f"Bearer {token}"}


def _setup_enrolled_student(make_teacher_user, make_student_user, make_class_session, make_enrollment, department=None):
    _teacher_user, teacher = make_teacher_user("teacher@example.com", "teacher-password", department=department)
    _student_user, student = make_student_user("student@example.com", "student-password", department=department)
    class_session = make_class_session(teacher=teacher)
    make_enrollment(student, class_session)
    return teacher, student, class_session


class TestListFeeStructures:
    """Gap closure: GET /fees/structures (Derived) backs the Admin Fee
    Dashboard's Record Payment dropdown."""

    def test_requires_admin_role(self, client, make_student_user):
        make_student_user("student@example.com", "correct-password")
        token = _login(client, "student@example.com", "correct-password")
        response = client.get("/api/v1/fees/structures", headers=_headers(token))
        assert response.status_code == 403

    def test_admin_lists_created_structures(self, client, make_admin_user, make_semester):
        make_admin_user("admin@example.com", "correct-password")
        token = _login(client, "admin@example.com", "correct-password")
        semester = make_semester()
        client.post(
            "/api/v1/fees",
            json={"semester_id": str(semester.id), "name": "Tuition", "amount": 5000, "due_date": "2030-01-01"},
            headers=_headers(token),
        )

        response = client.get("/api/v1/fees/structures", headers=_headers(token))
        assert response.status_code == 200
        body = response.json()
        assert body["total"] == 1
        assert body["items"][0]["name"] == "Tuition"


class TestCreateFeeStructure:
    def test_requires_admin_role(self, client, make_teacher_user):
        make_teacher_user("teacher@example.com", "correct-password")
        token = _login(client, "teacher@example.com", "correct-password")
        response = client.post(
            "/api/v1/fees", json={"semester_id": "00000000-0000-0000-0000-000000000000", "name": "X", "amount": 1, "due_date": "2030-01-01"}, headers=_headers(token)
        )
        assert response.status_code == 403

    def test_invalid_amount_rejected(self, client, make_admin_user, make_semester):
        make_admin_user("admin@example.com", "correct-password")
        semester = make_semester()
        token = _login(client, "admin@example.com", "correct-password")
        response = client.post(
            "/api/v1/fees",
            json={"semester_id": str(semester.id), "name": "Tuition", "amount": -5, "due_date": "2030-01-01"},
            headers=_headers(token),
        )
        assert response.status_code == 422

    def test_rule3_invoice_autogenerated_for_enrolled_student(
        self, client, make_admin_user, make_teacher_user, make_student_user, make_class_session, make_enrollment, make_semester
    ):
        make_admin_user("admin@example.com", "correct-password")
        teacher, student, class_session = _setup_enrolled_student(
            make_teacher_user, make_student_user, make_class_session, make_enrollment
        )
        admin_token = _login(client, "admin@example.com", "correct-password")

        response = client.post(
            "/api/v1/fees",
            json={
                "semester_id": str(class_session.semester_id),
                "name": "Tuition Fee",
                "amount": 10000,
                "due_date": "2030-01-01",
            },
            headers=_headers(admin_token),
        )
        assert response.status_code == 201
        assert response.json()["invoices_created"] == 1

        student_token = _login(client, "student@example.com", "student-password")
        me = client.get("/api/v1/fees/me", headers=_headers(student_token))
        assert me.status_code == 200
        assert me.json()["outstanding_balance"] == 10000.0
        assert me.json()["invoices"][0]["status"] == "unpaid"

    def test_department_scoped_fee_structure_excludes_other_department_students(
        self, client, make_admin_user, make_teacher_user, make_student_user, make_class_session, make_enrollment, make_semester, make_department
    ):
        make_admin_user("admin@example.com", "correct-password")
        dept_a = make_department()
        dept_b = make_department()
        teacher, student, class_session = _setup_enrolled_student(
            make_teacher_user, make_student_user, make_class_session, make_enrollment, department=dept_a
        )
        admin_token = _login(client, "admin@example.com", "correct-password")

        response = client.post(
            "/api/v1/fees",
            json={
                "department_id": str(dept_b.id),
                "semester_id": str(class_session.semester_id),
                "name": "Dept B Fee",
                "amount": 5000,
                "due_date": "2030-01-01",
            },
            headers=_headers(admin_token),
        )
        assert response.status_code == 201
        assert response.json()["invoices_created"] == 0

        student_token = _login(client, "student@example.com", "student-password")
        me = client.get("/api/v1/fees/me", headers=_headers(student_token))
        assert me.json()["invoices"] == []


class TestRecordPayment:
    def test_requires_admin_role(self, client, make_student_user):
        make_student_user("student@example.com", "correct-password")
        token = _login(client, "student@example.com", "correct-password")
        response = client.post(
            "/api/v1/fees/payments",
            json={"student_id": "00000000-0000-0000-0000-000000000000", "fee_structure_id": "00000000-0000-0000-0000-000000000000", "amount": 1, "payment_date": "2026-01-01T00:00:00Z"},
            headers=_headers(token),
        )
        assert response.status_code == 403

    def test_full_payment_workflow_and_overpayment_rejection(
        self, client, make_admin_user, make_teacher_user, make_student_user, make_class_session, make_enrollment
    ):
        make_admin_user("admin@example.com", "correct-password")
        teacher, student, class_session = _setup_enrolled_student(
            make_teacher_user, make_student_user, make_class_session, make_enrollment
        )
        admin_token = _login(client, "admin@example.com", "correct-password")
        student_token = _login(client, "student@example.com", "student-password")

        fs = client.post(
            "/api/v1/fees",
            json={"semester_id": str(class_session.semester_id), "name": "Tuition", "amount": 10000, "due_date": "2030-01-01"},
            headers=_headers(admin_token),
        ).json()

        # Partial payment.
        pay1 = client.post(
            "/api/v1/fees/payments",
            json={"student_id": str(student.id), "fee_structure_id": fs["id"], "amount": 4000, "payment_date": "2026-06-01T00:00:00Z"},
            headers=_headers(admin_token),
        )
        assert pay1.status_code == 201

        me = client.get("/api/v1/fees/me", headers=_headers(student_token))
        assert me.json()["outstanding_balance"] == 6000.0
        assert me.json()["invoices"][0]["status"] == "partially_paid"

        # Rule 6: overpayment beyond outstanding balance rejected.
        overpay = client.post(
            "/api/v1/fees/payments",
            json={"student_id": str(student.id), "fee_structure_id": fs["id"], "amount": 6001, "payment_date": "2026-06-02T00:00:00Z"},
            headers=_headers(admin_token),
        )
        assert overpay.status_code == 409

        # Exact remaining balance succeeds and marks paid.
        pay2 = client.post(
            "/api/v1/fees/payments",
            json={"student_id": str(student.id), "fee_structure_id": fs["id"], "amount": 6000, "payment_date": "2026-06-03T00:00:00Z"},
            headers=_headers(admin_token),
        )
        assert pay2.status_code == 201

        me_paid = client.get("/api/v1/fees/me", headers=_headers(student_token))
        assert me_paid.json()["outstanding_balance"] == 0.0
        assert me_paid.json()["invoices"][0]["status"] == "paid"

        # Rule 9: fully paid invoice rejects further payment.
        pay3 = client.post(
            "/api/v1/fees/payments",
            json={"student_id": str(student.id), "fee_structure_id": fs["id"], "amount": 1, "payment_date": "2026-06-04T00:00:00Z"},
            headers=_headers(admin_token),
        )
        assert pay3.status_code == 409

    def test_no_invoice_returns_404(self, client, make_admin_user, make_student_user, make_semester):
        make_admin_user("admin@example.com", "correct-password")
        _student_user, student = make_student_user("student@example.com", "student-password")
        semester = make_semester()
        admin_token = _login(client, "admin@example.com", "correct-password")

        fs = client.post(
            "/api/v1/fees",
            json={"semester_id": str(semester.id), "name": "Tuition", "amount": 1000, "due_date": "2030-01-01"},
            headers=_headers(admin_token),
        ).json()
        assert fs["invoices_created"] == 0  # student not enrolled anywhere this semester

        response = client.post(
            "/api/v1/fees/payments",
            json={"student_id": str(student.id), "fee_structure_id": fs["id"], "amount": 100, "payment_date": "2026-01-01T00:00:00Z"},
            headers=_headers(admin_token),
        )
        assert response.status_code == 404


class TestGetMyFees:
    def test_requires_student_or_parent_role(self, client, make_admin_user):
        make_admin_user("admin@example.com", "correct-password")
        token = _login(client, "admin@example.com", "correct-password")
        response = client.get("/api/v1/fees/me", headers=_headers(token))
        assert response.status_code == 403

    def test_rule12_parent_with_link_can_view(
        self,
        client,
        make_admin_user,
        make_teacher_user,
        make_student_user,
        make_parent_user,
        make_class_session,
        make_enrollment,
        link_parent_student,
    ):
        make_admin_user("admin@example.com", "correct-password")
        teacher, student, class_session = _setup_enrolled_student(
            make_teacher_user, make_student_user, make_class_session, make_enrollment
        )
        _parent_user, parent = make_parent_user("parent@example.com", "parent-password")
        link_parent_student(parent, student)
        admin_token = _login(client, "admin@example.com", "correct-password")

        client.post(
            "/api/v1/fees",
            json={"semester_id": str(class_session.semester_id), "name": "Tuition", "amount": 1000, "due_date": "2030-01-01"},
            headers=_headers(admin_token),
        )

        parent_token = _login(client, "parent@example.com", "parent-password")
        response = client.get("/api/v1/fees/me", params={"student_id": str(student.id)}, headers=_headers(parent_token))
        assert response.status_code == 200
        assert response.json()["outstanding_balance"] == 1000.0

    def test_rule12_parent_without_link_returns_403(self, client, make_parent_user, make_student_user):
        make_parent_user("parent@example.com", "parent-password")
        _student_user, student = make_student_user("student@example.com", "student-password")
        token = _login(client, "parent@example.com", "parent-password")
        response = client.get("/api/v1/fees/me", params={"student_id": str(student.id)}, headers=_headers(token))
        assert response.status_code == 403


class TestGetPaymentHistory:
    def test_requires_admin_or_parent_role(self, client, make_student_user):
        _student_user, student = make_student_user("student@example.com", "student-password")
        token = _login(client, "student@example.com", "student-password")
        response = client.get(f"/api/v1/fees/payments/{student.id}", headers=_headers(token))
        assert response.status_code == 403

    def test_admin_can_view_any_student(self, client, make_admin_user, make_student_user):
        make_admin_user("admin@example.com", "correct-password")
        _student_user, student = make_student_user("student@example.com", "student-password")
        token = _login(client, "admin@example.com", "correct-password")
        response = client.get(f"/api/v1/fees/payments/{student.id}", headers=_headers(token))
        assert response.status_code == 200


class TestGetOverdueAccounts:
    def test_requires_admin_role(self, client, make_student_user):
        make_student_user("student@example.com", "correct-password")
        token = _login(client, "student@example.com", "correct-password")
        response = client.get("/api/v1/fees/overdue", headers=_headers(token))
        assert response.status_code == 403

    def test_past_due_unpaid_invoice_listed(
        self, client, make_admin_user, make_teacher_user, make_student_user, make_class_session, make_enrollment
    ):
        make_admin_user("admin@example.com", "correct-password")
        teacher, student, class_session = _setup_enrolled_student(
            make_teacher_user, make_student_user, make_class_session, make_enrollment
        )
        admin_token = _login(client, "admin@example.com", "correct-password")
        client.post(
            "/api/v1/fees",
            json={"semester_id": str(class_session.semester_id), "name": "Tuition", "amount": 2000, "due_date": "2020-01-01"},
            headers=_headers(admin_token),
        )

        response = client.get("/api/v1/fees/overdue", headers=_headers(admin_token))
        assert response.status_code == 200
        accounts = response.json()["overdue_accounts"]
        assert len(accounts) == 1
        assert accounts[0]["amount_due"] == 2000.0
        assert accounts[0]["days_overdue"] > 0
        # Final-polish fix: the Admin Fee Dashboard must show a display
        # name, not just the raw student_id.
        assert accounts[0]["student_name"] == "Test Student"


class TestGetInvoice:
    def test_student_cannot_download_others_invoice(
        self, client, make_admin_user, make_teacher_user, make_student_user, make_class_session, make_enrollment
    ):
        make_admin_user("admin@example.com", "correct-password")
        teacher, student, class_session = _setup_enrolled_student(
            make_teacher_user, make_student_user, make_class_session, make_enrollment
        )
        admin_token = _login(client, "admin@example.com", "correct-password")
        client.post(
            "/api/v1/fees",
            json={"semester_id": str(class_session.semester_id), "name": "Tuition", "amount": 1000, "due_date": "2030-01-01"},
            headers=_headers(admin_token),
        )
        me = client.get("/api/v1/fees/me", headers=_login_and_headers(client, "student@example.com", "student-password"))
        invoice_id = me.json()["invoices"][0]["invoice_id"]

        _other_user, _other_student = make_student_user("other@example.com", "other-password")
        other_token = _login(client, "other@example.com", "other-password")
        response = client.get(f"/api/v1/fees/invoices/{invoice_id}", headers=_headers(other_token))
        assert response.status_code == 403

    def test_own_invoice_downloads_as_pdf(
        self, client, make_admin_user, make_teacher_user, make_student_user, make_class_session, make_enrollment
    ):
        make_admin_user("admin@example.com", "correct-password")
        teacher, student, class_session = _setup_enrolled_student(
            make_teacher_user, make_student_user, make_class_session, make_enrollment
        )
        admin_token = _login(client, "admin@example.com", "correct-password")
        client.post(
            "/api/v1/fees",
            json={"semester_id": str(class_session.semester_id), "name": "Tuition", "amount": 1000, "due_date": "2030-01-01"},
            headers=_headers(admin_token),
        )
        student_token = _login(client, "student@example.com", "student-password")
        me = client.get("/api/v1/fees/me", headers=_headers(student_token))
        invoice_id = me.json()["invoices"][0]["invoice_id"]

        response = client.get(f"/api/v1/fees/invoices/{invoice_id}", headers=_headers(student_token))
        assert response.status_code == 200
        assert response.headers["content-type"] == "application/pdf"
        assert response.content.startswith(b"%PDF")


def _login_and_headers(client, email, password):
    return _headers(_login(client, email, password))
